apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  ANTHROPIC_API_KEY: "{{ .Values.secrets.anthropicApiKey }}"
  SERPAPI_KEY: "{{ .Values.secrets.serpapiKey }}"
